package com.microS.policymanagement.models;

public enum CoverageOptions {
    FIRE,
    THEFT,
    THIRD_PARTY_LIABILITY,

    COURTESY_CAR,
    FLOOD,
    EARTHQUAKE,
    LOSS_OF_PERSONAL_EFFECTS,
     GEOGRAPHICAL_LIMIT,
     PERSONAL_INJURY,
     PASSENGER_LIABILITY,
     THEFT_FIRE_VEHICLE_DAMAGE,
     THIRD_PARTY_PERSONS_INJURY, NONE,
}
